module.exports.THOROUGHFARE_PROPS = ['DEPENDENT_THOROUGHFARE_NAME', 'THOROUGHFARE_NAME']

module.exports.BUILDING_NAME_PROPS = ['SUB_BUILDING_NAME', 'BUILDING_NAME']

module.exports.LOCALITY_PROPS = ['DOUBLE_DEPENDENT_LOCALITY', 'DEPENDENT_LOCALITY']

module.exports.DELIMITER = ', '
