version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.4-jdk-stretch-node-browsers
      - image: circleci/redis
    environment:
      PORT: 8080
      SESSION_SECRET: notsosecret
      WIREMOCK_PORT: 8090
      WIREMOCK_URL: http://localhost:8090
      USE_UNSECURE_COOKIE: true
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "d5:78:74:e9:5c:24:0d:5e:be:f7:91:8a:5b:ba:1d:93"
      - run:
          name: start chrome
          command: google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
      - restore-cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - restore-cache:
          key: bin-cache-{{ checksum "test_versions.properties" }}
      - run:
          name: npm install global
          command: sudo npm install -g standard tape nyc
      - run:
          name: npm install
          command: npm install
      - run:
          name: test
          command: npm test
      - run:
          name: coverage
          command: npm run coverage
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - save_cache:
          key: bin-cache-{{ checksum "test_versions.properties" }}
          paths:
            - ./bin
      - run:
          name: copy docs
          command: mkdir -p build/reports && cp src/documentation/gh-pages/index.html build/reports/ && ls build/reports/
      - persist_to_workspace:
          root: build
          paths:
            - reports/*
  deploy:
    docker:
      - image: circleci/node:10.16.0-browsers
    environment:
      SMOKE_TESTS: ./ci_scripts/smoke_tests.sh
      BIN_DIR: ./bin
      REPO_NAME: htbhf-applicant-web-ui
      APP_NAME: apply-for-healthy-start
      APP_PATH: .
      CF_DOMAIN: london.cloudapps.digital
      CF_PUBLIC_DOMAIN: london.cloudapps.digital
      CF_ORG: department-of-health-and-social-care
      CF_API: api.london.cloud.service.gov.uk
      BINTRAY_ROOT_URL: https://dl.bintray.com/departmentofhealth-htbhf/maven/uk/gov/dhsc/htbhf
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "24:13:d2:2d:5d:77:ed:bb:5e:7b:be:b5:3e:e0:aa:5c"
      - attach_workspace:
          at: build/reports/
      - attach_workspace:
          at: bin/
      - restore-cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: start chrome
          command: google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
      - run:
          name: npm install global
          command: sudo npm install -g standard tape nyc
      - run:
          name: npm install
          command: npm install
      - run:
          name: deploy to dev
          command: ./ci_scripts/ci_deploy.sh
      - run:
          name: Install gh-pages
          command: sudo npm install -g --silent gh-pages@2.0.1
      - run:
          name: Configure git email
          command: git config user.email "dhsc-htbhf-support@equalexperts.com"
      - run:
          name: Configure git name
          command: git config user.name "ci-build"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dist build/reports --message "[ci skip]"
      - run:
          name: ls bin/deployment-scripts/
          command: ls bin/deployment-scripts/
      - run:
          name: make scripts executable
          command: chmod +x ./bin/deployment-scripts/*.sh && chmod +x ./bin/deployment-scripts/management-scripts/*.sh && chmod +x ./ci_scripts/*.sh
      - run:
          name: Create tag
          command: ./ci_scripts/tag_version.sh
      - run:
          name: Set app version
          command: |
            echo "export APP_VERSION=$(sed -nE 's/^[ \\t]*"version": "([0-9]{1,}\.[0-9]{1,}\.[0-9x]{1,})",$/\1/p' package.json;)" >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Trigger cd build
          command: ./bin/deployment-scripts/management-scripts/trigger_circleci_cd_to_deploy_node_app.sh
      - persist_to_workspace:
          root: bin
          paths:
            - ./*

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore: gh-pages
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master

