module.exports.YES = 'yes'
module.exports.NO = 'no'
module.exports.CHECK_URL = '/check'
module.exports.CONFIRM_URL = '/confirm'
module.exports.UNSUCCESSFUL_APPLICATION = '/unsuccessful-application'
module.exports.ELIGIBLE = 'ELIGIBLE'
